name: tugasakhir_tpm
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  geolocator: ^10.1.0
  sensors_plus: ^3.0.0
  flutter_local_notifications: ^16.0.0
  google_places_flutter: ^2.0.9
  sqflite: ^2.2.3
  provider: ^6.0.0
  intl: ^0.18.0
  timezone: ^0.9.2
  crypto: ^3.0.2
  shared_preferences: ^2.0.0
  url_launcher: ^6.1.0
  image_picker: ^1.0.4
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
